### ISSUE TITLE
pkqs90 - Chainlink datafeed may be stale and incorrect

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#110] opened 2024-05-31 15:26 UTC
pkqs90

medium

# Chainlink datafeed may be stale and incorrect

## Summary

There are two issues related to the chainlink datafeed:

1. The current datafeed uses 3 day for staleness check, but the update period for EUR/USD on arbitrum is 1 hour.
2. It does not consider the builtin circuit breaker.

### 1. Staleness check

First let's talk about the staleness check issue.

This protocol is deployed on both Ethereum and Arbitrum, and the datafeed is used for EUR/USD and IB01/USD. According to the readme, the current staleness check is set to 3 days because IB01/USD *will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale if more than three days have passed*.

However, this is not how chainlink works. Even though the market price is only updated during weekdays, the price is still updated every X seconds **on-chain**, regardless if the market price is updated or not.

We can take EUR/USD on Arbitrum for an example: https://data.chain.link/feeds/arbitrum/mainnet/eur-usd. If we hover on "Trigger parameters", we can see it says "*A new answer is written when the offchain data moves more than the deviation threshold or 3600 seconds have passed since the last answer was written onchain*".

Just to be sure, we can read the `getRoundData()` function for its aggregator https://arbiscan.io/address/0xA14d53bC1F1c0F31B4aA3BD109344E5009051a84#readContract. Pass 18446744073709580880 and 18446744073709580881 as `_roundId` and we can see the update timestamp is 1716631204 (GMT, Saturday, May 25, 2024 10:00:04 AM) and 1716634806 (GMT, Saturday, May 25, 2024 11:00:06 AM). Notice the time difference is 1 hour and it is on a weekend.

Now we have proved that the aggregator is updated every hour on Arbitrum for EUR/USD, having a hardcoded 3 days staleness check is simply too long.

### 2. Circuit breaker

Then let's talk about the circuit breaker issue. This is of less impact, but I'd like to bring it up as well.

The EUR/USD aggregator contains a circuit breaker of minAnswer == 0.1, maxAnswer == 100 for EUR/USD on ethereum mainnet. We can check it up by the [aggregator](https://etherscan.io/address/0x02F878A94a1AE1B15705aCD65b5519A46fe3517e#readContract) address in EUR/USD [price feed](https://etherscan.io/address/0xb49f677943BC038e9857d61E7d053CaA2C1734C1#readContract). The minAnswer is 1e7, maxAnswer is 1e10, with 8 decimals.

This means if EUR/USD falls below 0.1 or rises above 100, the price feed would take 0.1 or 100 as the answer, which is unexpected.

The current price is 1.0824, and reaching such limit is unlikely to happen, but it would be nice to have a check for it.

```solidity
    function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```

## Impact

1. Staleness check is too large for EUR/USD pair on arbitrum.
2. There is no handling logic if the prices reaches below minAnswer or above maxAnswer.

Both would cause the incorrect calculation of minimum deposit amount for depositVault.

## Code Snippet

- https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64-L80

## Tool used

Manual review

## Recommendation

1. Do not hardcode 3 days as staleness check. Make it a configurable parameter, and set it to 3 hours for EUR/USD on Arbitrum.
2. Introduce a minAnswer and maxAnswer circuit breaker check.

**Comment by nevillehuang** [comment] 2024-06-07 19:47
Escalate. This issue is at best low severity. 

1. Call flow which `_getDataInBase18()` is only called in:
`getDataInBase18()` --> [`minAmountToDepositInUsd()`](https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/DepositVault.sol#L137C14-L141) --> `_validateAmountUsdIn` --> `deposit`. The only purpose of this check is to ensure a minimum amount of EUR value worth is deposited, which is set at 100_000 EUR value worth. There will never be any funds lost here even if the datafeed is stale, since user depositing still needs to commit the funds (at most a slight difference/gap allowed). Backend kyc checks will also mint amounts accordingly.

2. Known assumption in contest details:

> IB01/USD Price from Chainlink is RESTRICTED, as their documentation states that the price will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale if more than three days have passed.

**Comment by sherlock-admin3** [comment] 2024-06-07 19:47
> Escalate. This issue is at best low severity. 
> 
> 1. Call flow which `_getDataInBase18()` is only called in:
> `getDataInBase18()` --> [`minAmountToDepositInUsd()`](https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/DepositVault.sol#L137C14-L141) --> `_validateAmountUsdIn` --> `deposit`. The only purpose of this check is to ensure a minimum amount of EUR value worth is deposited, which is set at 100_000 EUR value worth. There will never be any funds lost here even if the datafeed is stale, since user depositing still needs to commit the funds (at most a slight difference/gap allowed). Backend kyc checks will also mint amounts accordingly.
> 
> 2. Known assumption in contest details:
> 
> > IB01/USD Price from Chainlink is RESTRICTED, as their documentation states that the price will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale if more than three days have passed.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xMR0** [comment] 2024-06-08 02:41
Escalate

This is valid Medium severity issue.

The issue correctly highlights the wrong heartbeat or staleness check used in contract. 

For example: For EUR/USD at Ethereum, Chainlink specifically states that:

> A new answer is written when the offchain data moves more than the deviation threshold or 86400 seconds have passed since the last answer was written on chain.

So the assumption mentioned in readme about prices being stale i.e `we assume the price is only stale if more than three days have passed` is incorrect.

The `_HEALTHY_DIFF` must use `24 hours` in Data feed contracts to align more closely with the Chainlink heartbeat on Ethereum, enhancing the relevance of the price data and `1 hours` for Arbitrum mainnet.

**Comment by sherlock-admin3** [comment] 2024-06-08 02:41
> Escalate
> 
> This is valid Medium severity issue.
> 
> The issue correctly highlights the wrong heartbeat or staleness check used in contract. 
> 
> For example: For EUR/USD at Ethereum, Chainlink specifically states that:
> 
> > A new answer is written when the offchain data moves more than the deviation threshold or 86400 seconds have passed since the last answer was written on chain.
> 
> So the assumption mentioned in readme about prices being stale i.e `we assume the price is only stale if more than three days have passed` is incorrect.
> 
> The `_HEALTHY_DIFF` must use `24 hours` in Data feed contracts to align more closely with the Chainlink heartbeat on Ethereum, enhancing the relevance of the price data and `1 hours` for Arbitrum mainnet.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by CarlosAlegreUr** [comment] 2024-06-08 09:35
> Escalate
> 
> This is valid Medium severity issue.
> 
> The issue correctly highlights the wrong heartbeat or staleness check used in contract.
> 
> For example: For EUR/USD at Ethereum, Chainlink specifically states that:
> 
> > A new answer is written when the offchain data moves more than the deviation threshold or 86400 seconds have passed since the last answer was written on chain.
> 
> So the assumption mentioned in readme about prices being stale i.e `we assume the price is only stale if more than three days have passed` is incorrect.
> 
> The `_HEALTHY_DIFF` must use `24 hours` in Data feed contracts to align more closely with the Chainlink heartbeat on Ethereum, enhancing the relevance of the price data and `1 hours` for Arbitrum mainnet.

I agree, on top that also mention that the MarketHours of chainlink feeds are not treated properly. The treatment of chainlink feeds is clearly incorrect for various reasons. An extra one not mentioned here can be found in my issue submitted marked as dupplicate: #20

**Comment by CarlosAlegreUr** [comment] 2024-06-08 17:28
> > Escalate
> > This is valid Medium severity issue.
> > The issue correctly highlights the wrong heartbeat or staleness check used in contract.
> > For example: For EUR/USD at Ethereum, Chainlink specifically states that:
> > > A new answer is written when the offchain data moves more than the deviation threshold or 86400 seconds have passed since the last answer was written on chain.
> > 
> > 
> > So the assumption mentioned in readme about prices being stale i.e `we assume the price is only stale if more than three days have passed` is incorrect.
> > The `_HEALTHY_DIFF` must use `24 hours` in Data feed contracts to align more closely with the Chainlink heartbeat on Ethereum, enhancing the relevance of the price data and `1 hours` for Arbitrum mainnet.
> 
> I agree, on top that also mention that the MarketHours of chainlink feeds are not treated properly. The treatment of chainlink feeds is clearly incorrect for various reasons. An extra one not mentioned here can be found in my issue submitted marked as dupplicate: #20

The Market Hours issue is not mentioned here but its is mentioned in mine #20 , it has a different fixing method and the price staleness comes from another property of the EUR/USD data feed. I wonder if that is enough to make my finding **not a duplicate** of this one. Im not sure about Sherlock rule regarding the problems with Data feeds but if sequencer and hearbeat problems can be sent separately without being duplicated, I think my MarketHours check should also be considered different.

Btw as of writing this comment, (Saturday 8 of June. around 19:30pm for me) currently if we go to the feed on Ethereum we can see that it has not been updated since the market closed on Friday. [Feed here](https://etherscan.io/address/0xb49f677943BC038e9857d61E7d053CaA2C1734C1#readContract) returned `updatedAt = 1717788407`, which you can see in this [UNIX timestamp convertor](https://www.unixtimestamp.com/) that it means `Fri Jun 07 2024 21:26:47 GMT+0200 (Central European Summer Time)`

**Comment by nevillehuang** [comment] 2024-06-08 19:16
All the escalation arguments highlights the inconsistencies without exploring impact aligning with sherlock medium severity guidelines, that it it must break core contract functionality, cause a DoS or a loss of funds. 

The worse case impact here is allowing a slight difference in minimum USDC deposited, which meets none of the above impacts. You can’t call a slight inconsistency in a minimum deposit check breaking core contract functionality, even more so when the minting of mTBILLS are ultimately decided off-chain.

**Comment by 0xSandyy** [comment] 2024-06-09 03:41
Hi, @nevillehuang 

``_HEALTHY_DIFF`` is set to ``3 days`` instead of ``1 days`` for ``EUR/USD`` for Ethereum.

Thus, The price feed will return stale price for 2 days. EUR/USD has [deviation threshold](https://data.chain.link/feeds/ethereum/mainnet/eur-usd) of 0.15% and the minimum amount to deposit is 100,000 Euros. Thus price can move up to 0.149% in 2 days before it is updated again.
```solidity
0.149 / 100 * 100000 = 149$
```
Max amount of 149$ can move up and down for the minimum deposit amount from the actual market rate while depositing due to price being stale for 2 days. This is loss of funds for either protocol or the depositor at the deposit time.

**Comment by 0xMR0** [comment] 2024-06-09 07:32
> All the escalation arguments highlights the inconsistencies without exploring impact aligning with sherlock medium severity guidelines, that it it must break core contract functionality, cause a DoS or a loss of funds.
> 
> The worse case impact here is allowing a slight difference in minimum USDC deposited, which meets none of the above impacts. You can’t call a slight inconsistency in a minimum deposit check breaking core contract functionality, even more so when the minting of mTBILLS are ultimately decided off-chain.

Inconsistencies? The issues and escalations are stressing on wrong use of heartbeat which is `3 times` than of Chainlink's heartbeat for price feeds for `Ethereum` and `72 times` for `Arbitrum`. The impact is already described in issues. Further, the protocol considers chainlink price feeds admin as restricted which makes the issue more important to mitigate with correct heartbeat.

In past, Similar/long heartbeat issues are considered as Medium severity at Sherlock where the rules were same for Medium severity issues.

What should be `_HEALTHY_DIFF ` according to you for Ethereum/Arbitrum? as we already proved the protocol teams(3 days) assumption incorrect with above comments.

**Comment by pronobis4** [comment] 2024-06-09 09:22
The sponsor allows 3 days because it validates everything off-chain, so each such application should have a low value.
This is basically a project that does everything off-chain, so each such information is additionally validated before it has any financial consequences.
Normally I would agree that it should be medium, but in this case it's max low/informative.

**Comment by sherlock-admin2** [comment] 2024-06-10 10:49
The protocol team fixed this issue in the following PRs/commits:
https://github.com/RedDuck-Software/midas-contracts/pull/46

**Comment by pronobis4** [comment] 2024-06-10 13:43
one more duplicate #194

**Comment by peterP1998** [comment] 2024-06-10 18:51
and one more duplicate guys https://github.com/sherlock-audit/2024-05-midas-judging/issues/194 @sherlock-admin2 @sherlock-admin3 @sherlock-admin

**Comment by WangSecurity** [comment] 2024-06-12 16:16
Firstly, #194 was submitted as low initially, hence, it cannot be assigned medium severity now.

Secondly, need clarification which price feeds will be used? As I understand, IB01/USD price feed will be used based on README, and as I understand from the submission EUR/USD price feed will be used as well and I assume USDC/USD as well, correct? And which of them are going to be used via `_getDataInBase18`, all of them?

**Comment by Kalogerone** [comment] 2024-06-12 17:44
> Firstly, #194 was submitted as low initially, hence, it cannot be assigned medium severity now.
> 
> Secondly, need clarification which price feeds will be used? As I understand, IB01/USD price feed will be used based on README, and as I understand from the submission EUR/USD price feed will be used as well and I assume USDC/USD as well, correct? And which of them are going to be used via `_getDataInBase18`, all of them?

Actually there is no mention of a USDC/USD datafeed if I recall correctly. Also, only the EUR/USD datafeed will be actually used as mentioned by the sponsors despite the `README`. Quoting a reply from a sponsor:

"This is a good question. Actually, we should not have mentioned the IB01 feed. This one is not used atm. It was part of an old version where we were doing some instant minting.

We are not doing that with this codebase"

Also, the IB01/USD datafeed is not available on Arbitrum network, which I reported in [#89](https://github.com/sherlock-audit/2024-05-midas-judging/issues/89) just in case because it was mentioned in the `README` and my report got `excluded`, that's why I think it's fair for the IB01/USD feed not to be taken into consideration.

**Comment by Afriaudit** [comment] 2024-06-13 09:17
The USDC/USD datafeed wasnt used sponsor stated in the README that "The system currently assumes that the price of one USDC is equal to one dollar"

**Comment by WangSecurity** [comment] 2024-06-13 22:39
As I see from the code, the only price feed that is going to be used is EUR/USD. 

Firstly, about the stale data check. I agree that 3 days is not optimal, but based on the README, this is the check that the protocol decides to use. Hence, I believe it is acceptable behaviour and is only a recommendation to use a smaller stale price check.

Secondly, about circuit breakers. Reports about circuit breakers are valid medium in that case. Note here, check the updated rules about circuit breaker checks for future contests.

Hence, this report will remain valid, cause it mentions the circuit breaker checks and the duplicates are: #49. Please list other duplicates if there are. Planning to accept the escalation.

**Comment by midori-fuse** [comment] 2024-06-14 01:48
#172 #142 #94 #64 #53 #49

**Comment by Tri-pathi** [comment] 2024-06-14 05:14
@WangSecurity 

For EUR/USD priceFeed

In Mainnet - `minAnswer` is 1e7  and `maxAnswer` is 1e10, with 8 decimals. which turns out to be 0.1 and 100 

In Arbitrum - `minAnswer` is 1e6  and `maxAnswer` is 1e11, with 8 decimals. which turns out to be 0.01 and 1000

That means, in range of [0.01, 1000] priceFeed will give correct results in Arbitrum. What is the likelihood that EUR/USD price will go out of this range in both chains ? 

Also [Chainlink](https://docs.chain.link/data-feeds#check-the-latest-answer-against-reasonable-limits) documentation says - `On most data feeds, these values are no longer used and they do not stop your application from reading the most recent answer ` 

Which makes these family of issues low/invalid ?

**Comment by ZdravkoHr** [comment] 2024-06-14 06:04
@WangSecurity, I think the protocol said 3 days is okay because the team didn't actually know there were differences between Arbitrum and Ethereum. The gap from 1 hour to 3 days is a big period of time.

**Comment by 0xhsp** [comment] 2024-06-14 07:20
> As I see from the code, the only price feed that is going to be used is EUR/USD.
> 
> Firstly, about the stale data check. I agree that 3 days is not optimal, but based on the README, this is the check that the protocol decides to use. Hence, I believe it is acceptable behaviour and is only a recommendation to use a smaller stale price check.
> 
> Secondly, about circuit breakers. Reports about circuit breakers are valid medium in that case. Note here, check the updated rules about circuit breaker checks for future contests.
> 
> Hence, this report will remain valid, cause it mentions the circuit breaker checks and the duplicates are: #49. Please list other duplicates if there are. Planning to accept the escalation.


`minAnswer ` and `maxAnswer ` are deprecated, hence reports about circuit breakers are invalid

**Comment by maushish** [comment] 2024-06-14 10:54
@0xhsp please share the resource where it has been mentioned that `_minAnswer` & `_maxAnswer` has been deprecated because here in the [code](https://github.com/smartcontractkit/libocr/blob/9e4afd8896f365b964bdf769ca28f373a3fb0300/contract/AccessControlledOffchainAggregator.sol#L33) that chainlink is using for aggregator this seems to still in use.

**Comment by maushish** [comment] 2024-06-14 10:58
@Tri-pathi please share your resource of your first argument 
>For EUR/USD priceFeed
>In Mainnet - minAnswer is 1e7 and maxAnswer is 1e10, with 8 decimals. which turns out to be 0.1 and 100
>In Arbitrum - minAnswer is 1e6 and maxAnswer is 1e11, with 8 decimals. which turns out to be 0.01 and 1000
>That means, in range of [0.01, 1000] priceFeed will give correct results in Arbitrum. What is the likelihood that EUR/USD price will go out of this range in both chains ?

Your second argument seems to be invalid as there is an assumption that the *most datafeeds* that you are talking about involves EUR/USD.

**Comment by 0xMR0** [comment] 2024-06-14 11:29
> As I see from the code, the only price feed that is going to be used is EUR/USD.
> 
> Firstly, about the stale data check. I agree that 3 days is not optimal, but based on the README, this is the check that the protocol decides to use. Hence, I believe it is acceptable behaviour and is only a recommendation to use a smaller stale price check.
> 
> Secondly, about circuit breakers. Reports about circuit breakers are valid medium in that case. Note here, check the updated rules about circuit breaker checks for future contests.
> 
> Hence, this report will remain valid, cause it mentions the circuit breaker checks and the duplicates are: #49. Please list other duplicates if there are. Planning to accept the escalation.

Not all assumptions of Sponsor are correct. We, Auditors are here to correct them and it is one of such issue. On Arbitrum, for said price feed, the heartbeat is `1 hours` and the contracts has hardcoded `3 days`. This hardcoded value is `72 times` more for Contracts to be deployed on Arbitrum mainnet. This is an incorrect value used and deviating from chainlink's recommendation and should not be justified with README assumption which is already proved wrong above. 

All of the issues should be considered valid, moreover, the sponsors have fixed the issue.

**Comment by pronobis4** [comment] 2024-06-14 11:42
Sure, it may be valid and the sponsor can fix it, but the impact may still be low.

**Comment by WangSecurity** [comment] 2024-06-14 18:22
Thank you for all these questions, will try to answer them now.

About long staleness check. I agree it's quite long, but it was mentioned in the README that it's okay. Yes, it was said in the context of IB01/USD price feed which is not used in the end. But, I believe in that sense, it's a design decision to implement such staleness check for all price feeds. That's why I believe reports about using smaller staleness check are design recommendations. Shouldn't we report such issues? We should. Does it make the finding M/H automatically? No, unfortunately. Saying that the sponsor doesn't know about the issue, I believe it's just an assumption. But, they said the chainlink doesn't update the price on weekends. Yes, but it was said in context of IB01/USD price feed which as I understand indeed doesn't update on the weekend (if it's wrong, please send the link to the price feed address). And for other price feeds is a design decision as an acceptable staleness check.

About circuit breakers. They're deprecated on **most** of the price feeds. Not on all of them. More information how to understand if it's deprecated for a certain price feed, you can find [here](https://stackoverflow.com/questions/78558661/which-chainlinks-price-feeds-still-have-minanswer-and-maxanswer-checks). Yes, the range for `minAnswer` and `maxAnswer` for EUR/USD is quite insane and there's extremely low likelihood for hitting them. But, neither medium severity nor high severity take likelihood into consideration as you can see by the definitions.

Hope that answers all of your questions. The decision remains the same, reject the escalation, but keep this report as valid medium with the following duplicates: https://github.com/sherlock-audit/2024-05-midas-judging/issues/172 https://github.com/sherlock-audit/2024-05-midas-judging/issues/142 https://github.com/sherlock-audit/2024-05-midas-judging/issues/94 https://github.com/sherlock-audit/2024-05-midas-judging/issues/64 https://github.com/sherlock-audit/2024-05-midas-judging/issues/53 https://github.com/sherlock-audit/2024-05-midas-judging/issues/49.

**Comment by nevillehuang** [comment] 2024-06-14 18:25
@WangSecurity Have you considered the only use case of the check I highlighted [here](https://github.com/sherlock-audit/2024-05-midas-judging/issues/110#issuecomment-2155453508). All minting of mTbills are done off-chain per docs, so are you saying this broken circuit breaker breaks core contract functionality, because I don’t see it that way given my comments.

**Comment by WangSecurity** [comment] 2024-06-14 18:37
Yes, I've taken it into consideration @nevillehuang. But, I'm not sure if it's appropriate here, but maybe you can help me understand it better. The chainlink price feed is used to convert EUR/USD, so for example, if EUR falls down dramatically  even below `minAnswer` for example. `minAnswer` is 0.01, but in this case price falls down to 0.001. Then the users deposit will be valued 10x (cause the actual price is 10 times smaller then `minAnswer`), which leads to incorrect accounting and assuming the user deposited 10x more. But, on the other hand, your point is that the conversion is done off-chain and maybe they already have mitigation for it, which we're not aware of cause we don't know how the off-chain mechanism works, correct?

**Comment by nevillehuang** [comment] 2024-06-14 18:42
@WangSecurity The minting mechanism is performed off-chain and is oos of this contest, so we would believe it is working as intended. That means even if on chain price used for solely the minimum deposit check is incorrect, the admins would do necessary checks offchain before performing the secondary step of minting and transfer of funds to users. If not the protocol will be self harming the NAV of mTBILLs

https://docs.midas.app/protocol-mechanics/how-it-works/issuance-and-redemption#how-issuance-works

**Comment by WangSecurity** [comment] 2024-06-14 18:44
Hm, fair point, thank you for bringing it up. Before making the final call on issue regarding circuit breakers, will take a bit of time to give it another thought.

**Comment by WangSecurity** [comment] 2024-06-16 11:13
After additional thought, I believe the following is correct (excuse me for stating the obvious and already mentioned, but I believe it will better express my decision):

1. Before actually minting mTBILL the protocol does an off-chain conversion of the deposited USDC into mTBILL.
2. The oracle is only used for the first time depositors and it checks if the deposit in USDC is higher than min deposit in EURO.
3. So, from my calculation is the following:
- If the actual price is 110 and `maxAnswer` is 100. For the sake of example, the min deposit is 10,000 euro. The min deposit check would return 1,000,000 (10,000 * 100), when the user wants to deposit 1,100,000 (min deposit based on the real price, 10,000 * 110). They will pass the check, even if they deposit less than 10,000, e.g. 9,500 deposit would be 1,045,000 which is above the minDeposit based on the `maxAnswer). But, I agree it's fair to assume that the protocol will check for it off-chain and there's no impact on on-chain data, because all the variables and event emissions will reflect the actual amount the user deposited.
- If the actual price is 0.001 and `minAnswer` is 0.01. For the sake of example, the min deposit is 10,000 Euro. The min deposit check would return 100 (10,000 * 0.01), when the user wants to deposit 10 (min deposit based on the real price, 10,000 * 0.001). In that case the check will revert for the first time depositor. They will have to deposit 10 times more to pass the check. That's quite unfair, cause the user has to be able to deposit based on that amount. But, this doesn't cause any loss of funds, and moreover, there are functions to either free specific users from the min deposit or change it to reflect a more realistic price than `minAnswer` or `maxAnswer`.

Hence, the decision is to accept the escalation and invalidate the issue.

**Comment by maushish** [comment] 2024-06-16 13:12
Hey @WangSecurity thanks for the response 
>If the actual price is 0.001 and minAnswer is 0.01. For the sake of example, the min deposit is 10,000 Euro. The min deposit check would return 100 (10,000 * 0.01), when the user wants to deposit 10 (min deposit based on the real price, 10,000 * 0.001). In that case the check will revert for the first time depositor. They will have to deposit 10 times more to pass the check. That's quite unfair, cause the user has to be able to deposit based on that amount. But, this doesn't cause any loss of funds, and moreover, there are functions to either free specific users from the min deposit or change it to reflect a more realistic price than minAnswer or maxAnswer.

I think this is a valid medium as you already mentioned users would have to deposit funds multiple times and sherlock rule already states:
![image](https://github.com/sherlock-audit/2024-05-midas-judging/assets/114429859/92c66afa-c5b6-44d4-834b-d61e1b16c5be)
This problem will be valid for some users and hence the impact will be of medium severity.
I am well aware of the functions that can either free specific users from the min deposit or change it to reflect a more realistic price than minAnswer or maxAnswer but as of now we have to take the current design as the final product.

**Comment by WangSecurity** [comment] 2024-06-16 16:31
I’m taking the current design of the protocol and I don’t see how it leads to either a loss of funds or renders a contract useless. The users are still able to deposit into the protocol, and I don’t see depositing funds multiple times instead of 1 is an issue. And I didn’t say they have to deposit more, I meant that the check would fail, cause it believes the price is 10x the actual price and it would revert only first depositors. But, can be mitigated by admins. Hence, I believe low severity is appropriate here.

The decision remains the same, planning to accept the escalation and invalidate the report.

**Comment by Tomiwasa0** [comment] 2024-06-16 18:53
@WangSecurity  Kindly read report #128, an edge case was described there

**Comment by WangSecurity** [comment] 2024-06-17 06:45
As far as I'm aware, IB01/USD price feed is not used, and EUR/USD (which is used) is updated frequently and there wouldn't be such a case.

The decision remains the same, accept the escalation and invalidate the issue.

**Comment by Tomiwasa0** [comment] 2024-06-18 06:26
@WangSecurity 
According to the readme provided

>IB01/USD Price from Chainlink is RESTRICTED, as their documentation states that the price will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale if more than three days have passed.

**Comment by WangSecurity** [comment] 2024-06-18 08:48
@Tomiwasa0 and factually only EUR/USD price feed is used in the code and it was discussed in the comments above. Hence, if there's no new information, please don't repeat the same arguments.

The decision remains the same, planning to accept the escalation and invalidate the report in a couple of hours.

**Comment by WangSecurity** [comment] 2024-06-18 15:30
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment] 2024-06-18 15:30
Escalations have been resolved successfully!

Escalation status:
- [nevillehuang](https://github.com/sherlock-audit/2024-05-midas-judging/issues/110/#issuecomment-2155453508): accepted
- [0xMR0](https://github.com/sherlock-audit/2024-05-midas-judging/issues/110/#issuecomment-2155770517): rejected

**Closed** 2024-06-18 15:30 UTC
Labels: Has Duplicates, Sponsor Confirmed, Will Fix, Escalated, Non-Reward

**Comment by sherlock-admin2** [comment] 2024-06-21 03:54
The Lead Senior Watson signed off on the fix.
